image:
  repository: ghcr.io/keepguard/srv-email-google-sender
  tag: "1.1.2"
  pullPolicy: IfNotPresent

service:
  port: 8601

resources:
  limits:
    memory: 256Mi
  requests:
    memory: 128Mi

env:
  appEnv: dev
  rabbitmqHost: "rabbitmq-service"
  rabbitmqPort: 5672

imagePullSecrets:
  - name: ghcr-secret
